// Disclaimers and legal-review banners for 282.
//
// The two strings STANDARD_DISCLAIMER and CONTRACT_PACK_FOOTER are used
// verbatim across the product and MUST NOT be edited without solicitor
// sign-off. They are exported as standalone constants so that other content
// modules (e.g. routing.ts) can compose them and a test can assert they are
// reused verbatim rather than re-typed.

/**
 * The standard automated-notice disclaimer. Shown alongside every regulatory
 * routing result and every tripwire warning. VERBATIM — do not alter.
 */
export const STANDARD_DISCLAIMER =
  "This is an automated information notice, not legal advice. Consider consulting a solicitor.";

/**
 * The footer printed at the foot of every contract pack. VERBATIM — do not
 * alter.
 */
export const CONTRACT_PACK_FOOTER =
  "Generated by 282. This document is a template and record. It is not legal advice. Take it to a solicitor before relying on it.";

export interface DisclaimerCopy {
  /** Verbatim standard automated-notice disclaimer. */
  standardDisclaimer: string;
  /** Verbatim contract-pack footer. */
  contractPackFooter: string;
  /** Banner shown at the head of every contract template. */
  solicitorReviewBanner: {
    label: string;
    title: string;
    body: string;
  };
}

export const disclaimers: Record<"en-GB", DisclaimerCopy> = {
  "en-GB": {
    standardDisclaimer: STANDARD_DISCLAIMER,
    contractPackFooter: CONTRACT_PACK_FOOTER,
    solicitorReviewBanner: {
      label: "For review by a solicitor",
      title: "Template document — have a solicitor review this before you rely on it",
      body: "This is a template prepared to help you record and evidence an agreement you have already reached. It has not been prepared for your specific circumstances and it is not legal advice. Before signing, relying on, or acting on this document, take it to a qualified solicitor for review. 282 does not draft, approve, or advise on any agreement.",
    },
  },
} as const;

export default disclaimers;
